mutation CreateStatusupdate($status: String!){
  createStatusupdate(
    createStatusupdateInput: {
      status: $status
    }
)
  {
    id
    status
    createdAt
    updatedAt
    user {
      id
      firstName
      lastName
    }
    team {
      id
      teamName
    }
  }
}
