query Team {
  team {
    id
    teamName
    statusupdates(limit: 50) {
      status
      createdAt
      id
      user {
        email
        firstName
        lastName
      }
    }
    users {
      id
      email
      firstName
      lastName
      statusupdates(limit: 1) {
        id
        createdAt
        status
        team {
          teamName
        }
      }
    }
  }
}
