# you can query `team` also without any input: team {...fields}
# limit is default 1 on the backend
query Team($limit: Int!) {
  team(queryTeamInput: {limit: $limit}) {
    teamName
    users {
      id
      firstName
      lastName
      email
      statusupdates {
        id
        createdAt
        status
      }
    }
  }
}
