# To remove user from team just don't pass $teamId
mutation updateUser($userId: String!, $teamId: String){
  updateUser(updateUserInput: {
    userId: $userId
    teamId: $teamId
  }) {
    id
    firstName
    lastName
    team {
      id
      teamName
    }
  }
}
