mutation CreateStatusupdate($status: String!, $updatetype: String){
  createStatusupdate(
    createStatusupdateInput: {
      status: $status
      updatetype: $updatetype
    }
  )
  {
    id
    status
    createdAt
    updatedAt
    user {
      id
      email
      firstName
      lastName
    }
    team {
      id
      teamName
    }
  }
}
