mutation Signup($firstName: String!, $lastName: String!, $email: String!, $password: String!){
  signup(
    createUserInput: {
      firstName: $firstName
      lastName: $lastName
      email: $email
      password: $password
    }
  ) {
    id
    email
  }
}
