query User {
  user {
    id
    firstName
    lastName
    email
    avatar
    createdAt
    updatedAt
    team {
      id
      teamName
    }
    statusupdates {
      id
      createdAt
      status
      updatetype {
        type
      }
    }
  }
}
